version: "3.1"

services:
    tgbot:
        container_name: engbot
        build:
            context: .
        command: python app.py
        restart: always

        env_file:
            - ".env"